USE zoo;


CREATE TABLE PERSON(
FullName VARCHAR(40) NOT NULL,
Street VARCHAR(50),
City VARCHAR(20),
PhoneNumber  INT(10),
EmailAddress VARCHAR(20),
DOB DATE,
CONSTRAINT PERSON_PK PRIMARY KEY (FullName));


CREATE TABLE VISITOR(
TicketNum INT(8) NOT NULL,
TicketType VARCHAR(250),
VisitDate DATE ,
VisitorFullName VARCHAR(40),
CONSTRAINT VISITOR_PK PRIMARY KEY(TicketNum),
CONSTRAINT VISITOR_FK FOREIGN KEY(VisitorFullName) REFERENCES PERSON(FullName) ON DELETE CASCADE ON UPDATE CASCADE);




CREATE TABLE EMPLOYEE(
EmployeeID VARCHAR(10) NOT NULL,
HireDate DATE,
EmployeeType  VARCHAR(20),
EmployeeFullName VARCHAR(40),
CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EmployeeID),
CONSTRAINT EMPLOYEE_FK FOREIGN KEY(EmployeeFullName) REFERENCES PERSON(FullName) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE OSTAFF(
StaffID VARCHAR(10) NOT NULL,
DeskNum INT(4),
Department  VARCHAR(20),
OEmpID VARCHAR(10),
CONSTRAINT OSTAFF_PK PRIMARY KEY(StaffID),
CONSTRAINT OSTAFF_FK FOREIGN KEY(OEmpID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE);



CREATE TABLE ZOOKEEPER(
KeeperID VARCHAR(10) NOT NULL,
ZEmpID VARCHAR(10),
CONSTRAINT ZOOKEEPER_PK PRIMARY KEY(KeeperID),
CONSTRAINT ZOOKEEPER_FK FOREIGN KEY(ZEmpID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE);




CREATE TABLE ZSKILLS(
KSkillID VARCHAR(10) NOT NULL,
Skill VARCHAR(50),
CONSTRAINT ZSKILLS_PK PRIMARY KEY(KSkillID, Skill),
CONSTRAINT ZSKILLS_FK FOREIGN KEY(KSkillID) REFERENCES ZOOKEEPER(KeeperID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE EXHIBIT(
ExhibitID INT(3) NOT NULL,
Name VARCHAR(20),
Location VARCHAR(20),
Hours VARCHAR(10),
CONSTRAINT EXHIBIT_PK PRIMARY KEY(ExhibitID));


CREATE TABLE FEEDING(
Species VARCHAR(100),
FoodType VARCHAR(50),
CONSTRAINT FEEDING_PK PRIMARY KEY (Species));


CREATE TABLE ANIMAL(
AnimalID VARCHAR(9) NOT NULL,
Name VARCHAR(20),
Kingdom VARCHAR(20),
Phylum VARCHAR(20),
Class VARCHAR(20),
Ordr VARCHAR(20),
Family VARCHAR(20),
Genus VARCHAR(20),
Species VARCHAR(100),
DateofBirth DATE,
DateofAdmission DATE,
CONSTRAINT ANIMAL_PK PRIMARY KEY (AnimalID),
CONSTRAINT ANIMAL_FK FOREIGN KEY (Species) REFERENCES FEEDING (Species) ON DELETE CASCADE ON UPDATE CASCADE);
